extends: airbnb-base
env: 
  mocha: true
rules:
  # Customize to throw error if code length exceed 150, ignore comments, strings and templateLiterals
  max-len:
    [error, { code: 150, ignoreComments: true, ignoreStrings: true, ignoreTemplateLiterals: true }]